### ISSUE TITLE
[FEATURE] Display and notify when there are conflicting files

### ISSUE THREAD

**Issue by LBF38** [LBF38/obsidian-syncthing-integration#11]
**Is your feature request related to a problem? Please describe.**
Time to time, when syncing files, it could happen that there are some files in conflict. Therefore, SyncThing manages correctly by creating new files (with specific patterns) that could be handle to resolve these conflicts between files.

**Describe the solution you'd like**
A first solution could be to make a list of all the files in conflicts. Moreover, the plugin should notify the user after syncing the files and that there are conflicts. By clicking the notification, the user should see a list of files in conflicts.

The next steps would be to be able to handle the conflicts in a specific Obsidian modal, showing the list of conflicting file and the original file. A difference between the selected version and the original would be seen on the middle. And the user could choose to add specific things among the different files in conflicts. (There could be more than two files in conflicts if we sync more than two devices).

**Describe alternatives you've considered**
The alternative is to use SyncThing out of Obsidian or to use other tools such as VS Code or other editors to show differences and make a choice.

**Additional context**
Some relevant sources could be the following Obsidian plugins that already implement a modal showing the difference between two files : 
- Version History Diff (Sync, File Recovery & Git) ([GitHub repo](https://github.com/kometenstaub/obsidian-version-history-diff))

**Comment by Mikle-Bond** [comment]
The behavior I would like to see is to show a "red flag" in status bar when viewing a file with known `sync-conflict` counterpart. There should be something like a "yellow flag" when sync conflicts exist, but this particular note is OK, and "green flag" when no conflicts found.

Having notifications is good, but I'm not always ready to resolve conflicts right away, and I can continue to use other notes. The only time I'm _really_ concerned about a conflict is when I'm editing a note with existing conflict. 

In this case, clicking on status bar should open the conflict in vertical split pane.

As a further improvement, There might be more than one conflict file, and conflict files themself can have conflict files (like `some-note.sync-conflict-20230925-053519-MIYKOGV.sync-conflict-20230926-081243-MIYKOGV.md`). To handle this, I'd find it useful if right clicking the status bar icon would list all known conflicts in this group, and allow opening any of them or all at once in split panes. In this case, clicking the icon should open only the "most recent timestamp" conflict file (as the best guess for most theoretically valuable).

Finally, there might be a situation, when only conflict file exists, without its "original" (i.e. `some-note.sync-conflict-20230925-053519-MIYKOGV.md` exists, but `some-note.md` is already deleted). In this case, status bar should suggest an option to quickly rename this file to its original (`some-note.md` in the example above). It **shouldn't** suggest deleting this file, as this is can be handled by Obsidian's native UI.

If these actions would be exposed via commands, that would be amazing. Something like:
- "List conflicts of this note"
- "Open all conflicts of this note as splits"
- "List all conflict files in vault"
- "Rename this conflict file to its original" (not shown if original exists)

**Comment by LBF38** [comment]
@Mikle-Bond Firstly, thank you for using my plugin and the feedback provided ! 

I agree with what you mentioned and I'll make my best to deliver this in next releases. 

Just to warn you, I work on this project in my free time, so it may take some time before new features are implemented.
Feel free to create a PR too !

**Comment by LBF38** [comment]
@Mikle-Bond I come back to you, as I've got more time to tackle this feature. I'm in the process of developing it. Here is a preview of some parts of the feature : 
![image](https://github.com/LBF38/obsidian-syncthing-integration/assets/96347823/e024abb4-7646-4769-bffa-ba3a9aa397d8)

Please feel free to give me more feedback or share more information about your point of view on this feature. 
Thx !

**Comment by LBF38** [comment]
That's exactly what I was thinking! Thought, I didn't know if it would be prettier or misleading. I'll implement it and we'll see.

I'm iterating on this feature and will be releasing it in the next few hours or days.

You'll soon be able to use it and give feedback in the meantime! 
Thx

**Comment by LBF38** [comment]
@Mikle-Bond I've merged the new status bar feature in `main` and it will be available in the next release.
Please feel free to reopen this issue if you see any bugs / errors on the feature.

PS: for now, there is no commands registered and there isn't the possibility to rename the conflict file to original file. I'm working on that point, as it has weird side effects.
