### ISSUE TITLE
Issue with how plugin tries to access HTTP

### ISSUE THREAD

**Issue by brimwats** [LBF38/obsidian-syncthing-integration#110]
Syncthing is at `localhost:8384` for me. This works on browser: 

![image](https://github.com/LBF38/obsidian-syncthing-integration/assets/73113656/f8e099d0-15b2-437a-b598-de4a52065477)

So I added it into the plugin settings there:

![image](https://github.com/LBF38/obsidian-syncthing-integration/assets/73113656/e05cc44d-419a-45ef-862d-d72ee328e690)

however when I click "open syncthing gui" the web browser tries to load `https://http//localhost:8384`, which obviously fails. 

This is maybe related to #94 as I get these errors:

![image](https://github.com/LBF38/obsidian-syncthing-integration/assets/73113656/c1d9057c-b770-4f9b-9f32-846f311bcafc)

**Comment by LBF38** [comment]
Thanks for reporting it ! My mistake, when I refactored it ! 

Note for me : https://github.com/LBF38/obsidian-syncthing-integration/blob/master/src/components/settings_view.svelte#L335-L338
