### ISSUE TITLE
[FEATURE] Support syncthing_macos install of syncthing

### ISSUE THREAD

**Issue by jsamuel1** [LBF38/obsidian-syncthing-integration#166]
**Is your feature request related to a problem? Please describe.**
When installing on macos using `brew install --cask syncthing`, the syncthing cli is installed into a subfolder of the application under `/Applications/Syncthing.app/Contents/Resources/syncthing/syncthing` , which is not in the system search path

**Describe the solution you'd like**
When on a mac, and syncthing cli is now found in the path, search for the Syncthing.app installation and set the instance under this app as the cli path, using the full pathname to execute the file.

**Describe alternatives you've considered**
An alternative is to install syncthing a second time into the path, though this would cause potential version conflicts.

**Comment by LBF38** [comment]
Thanks for your contribution ! You can add yourself to the all-contributors table on the README by using the [@all-contributors bot](https://allcontributors.org/docs/en/bot/usage), if you want.

**Comment by jsamuel1** [comment]
@all-contributors add @jsamuel1 for some macos code
