### ISSUE TITLE
[FEATURE] Support for ignored files or folders in Syncthing configuration

### ISSUE THREAD

**Issue by LBF38** [LBF38/obsidian-syncthing-integration#81]
**Is your feature request related to a problem? Please describe.**

Would love to manage the files and folders ignored by Syncthing in the Obsidian plugin.

**Describe the solution you'd like**

A list of all files/folders available in the vault, with a checkbox or toggle to select it.
Then, when selection is confirmed, the syncthing's configuration ignored file is generated or modified in consequence.
Finally, these files would not be synced across my devices because they are ignored by Syncthing configuration.

**Describe alternatives you've considered**

To modify it directly in the Syncthing GUI, while copying/remembering the name of the files I would like to ignore.
Tough UX.

**Screenshots**
![image](https://github.com/LBF38/obsidian-syncthing-integration/assets/96347823/6504847c-e362-4c3e-953b-d52137937ba8)

**Additional context**

Could be interesting to have a live preview of the ignored file shown below ? => easily doable w/ Svelte.

**Comment by GottZ** [comment]
I usually throw this in .stignore:
```
#include .stglobalignore
```

and currently have this in .stglobalignore:
```
**/node_modules
**/.git
**/obsidian-livesync
.obsidian/plugins/recent-files-obsidian/data.json
.obsidian/workspace.json
.obsidian/workspace-mobile.json
**/*workspace
```

it could be viable to also add a global ignore feature like I use in my environment, that persists automatically to other devices.

**Comment by LBF38** [comment]
For reference: https://publish.obsidian.md/hub/02+-+Community+Expansions/02.05+All+Community+Expansions/Auxiliary+Tools/Syncthing
=> tips on Syncthing config w/ Obsidian.
